// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcyddaxwzzyvkkrebahn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeWRkYXh3enp5dmtrcmViYWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTEwMTEsImV4cCI6MjA1OTUyNzAxMX0.38nLdjyhm9UQH-mcGnbeBL6Yd08-AlgNo2_f7U7DjKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);